# fly.toml app configuration file generated for ml-test on 2024-11-09T03:02:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ml-test'
primary_region = 'scl'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
